#!/bin/bash
echo "compiling C files"
gcc -ffreestanding \
	-mno-red-zone \
	-mno-80387 \
	-mno-mmx \
	-mno-3dnow \
	-mno-sse \
	-mno-sse2 \
	-Wall \
	-Wextra \
    -mcmodel=large \
    -c kernel/startup.c kernel/cpu.c \

mv startup.o bin/ && mv cpu.o bin/
echo "linking..."
ld -m elf_x86_64 \
    -nostdlib \
    -static \
    -pie \
    --no-dynamic-linker \
    -z text \
    -z max-page-size=0x1000 \
    -T linker.ld \
    -o disk/kernel.elf \
    bin/startup.o bin/cpu.o \

echo "building iso..."
xorriso -as mkisofs -b limine/limine-cd.bin -no-emul-boot \
-boot-load-size 4 -boot-info-table --efi-boot \
limine/limine-cd-efi.bin -efi-boot-part --efi-boot-image \
--protective-msdos-label disk -o my_iso.iso

echo "installing limine..."
sudo ./limine-deploy my_iso.iso

echo "SUCCESS"
